### ISSUE TITLE
Selecting Objects 

### ISSUE THREAD

**Issue by monasobh** [hpi-swa-teaching/PowerSqueak#83] opened 2019-05-02 09:16 UTC
As a presentation creator, I want to be able to select an item and see the handles only from this item. This helps to see where you're currently working at and makes it easier to resize an object. 

Acceptance criteria:

- [ ] select one object and see handles 
- [ ] deselect object by clicking on another object or anywhere on the slide - and don't see handles 

Estimated effort: 8?

**Comment by MrModder** [comment] 2019-05-02 12:49
Duplicate of: #48

**Closed by MrModder** 2019-05-02 12:49 UTC
Labels: enhancement, user story
